steps:

#- name: python:3.11
#  entrypoint: bash
#  args:
#    - -c
#    - |
#      pip install -r requirements.txt
#      export PYTHONPATH=.
#      pytest

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/test-falabella-ipg/cloud-run-source-deploy/procesar-ventas', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/test-falabella-ipg/cloud-run-source-deploy/procesar-ventas']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - run
    - deploy
    - procesar-ventas
    - --image=us-central1-docker.pkg.dev/test-falabella-ipg/cloud-run-source-deploy/procesar-ventas
    - --region=us-central1
    - --platform=managed
    - --allow-unauthenticated
    - --set-env-vars=PROJECT_ID=test-falabella-ipg,DATASET=falabellaplatform,TABLE=ventas_2

options:
  logging: CLOUD_LOGGING_ONLY
